/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.crudkontak.Frame;

import com.mycompany.crudkontak.model.User;
import com.mycompany.crudkontak.controller.Controller;
import java.util.List;
import java.util.ArrayList;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import  javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Acer SPIN
 */
public class FrameKontak extends javax.swing.JFrame {
    ResultSet resultData;
    /**
     * Creates new form FrameKontak
     */
    public FrameKontak() {
        
        initComponents();
        fillTable();
//        inputId.setVisible(false);
        namaAlert.setVisible(false); 
        telpAlert.setVisible(false);
        alamatAlert.setVisible(false);
        idLabel.setVisible(false);
    }
    private boolean validasiInput(User user){
        boolean nama = false;
        boolean telp = false;
        boolean alamat = false;
        boolean namaTextEmpty = user.getNama().equals("");
        boolean telpTextEmpty = user.getTelepon().equals("");
        boolean alamatTextEmpty = user.getAlamat().equals("");
        
        if(namaTextEmpty){
            namaAlert.setText("Hey Anda belum mengisi kolom ini!");
            namaAlert.setVisible(true);
        } else namaAlert.setVisible(false);
        
        if(telpTextEmpty){
            telpAlert.setText("Hey Anda belum mengisi kolom ini!");
            telpAlert.setVisible(true);
        }else telpAlert.setVisible(false);
        
        if(alamatTextEmpty){
            alamatAlert.setText("Hey Anda belum mengisi kolom ini!");
            alamatAlert.setVisible(true);
        }else alamatAlert.setVisible(false);
        
        nama = !namaTextEmpty;
        telp = !telpTextEmpty;
        alamat = !alamatTextEmpty;
        return nama && telp && alamat;
    }
    private void fillTable(){
        resultData = Controller.getData();
        Object data[][] = new Object[0][0];
        List<User> users = new ArrayList<User>();
        try {
            while (resultData.next()) {
            User user = new User();
            user.setId(resultData.getInt("id") + "");
            user.setNama(resultData.getString("nama"));
            user.setTelepon(resultData.getString("telepon"));
            user.setAlamat(resultData.getString("alamat"));
            users.add(user);  
            
        }
        } catch (Exception e) {
            e.getStackTrace();
        }
        data = new Object[users.size()][4];
        for(int i = 0; i < users.size(); i++){
            data[i][0] = users.get(i).getId();
            data[i][1] = users.get(i).getNama();
            data[i][2] = users.get(i).getTelepon();
            data[i][3] = users.get(i).getAlamat();
            System.out.println(users.get(i).getNama());
        }
        String judul[] = {"No","Nama", "Telepon", "Alamat"};
        JTable a = new JTable(data,judul);
        jTable1.setModel(new DefaultTableModel(data, judul));
        jScrollPane2.setViewportView(jTable1);
    }
    private void clearField(){
        inputNama.setText("");
        inputTelp.setText("");
        inputAlamat.setText("");
        idLabel.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputTelp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputAlamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        telpAlert = new javax.swing.JLabel();
        namaAlert = new javax.swing.JLabel();
        alamatAlert = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CRUD Buku Telepon");

        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama");

        inputTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTelpActionPerformed(evt);
            }
        });

        jLabel3.setText("Telepon");

        jLabel4.setText("Alamat");

        inputAlamat.setColumns(20);
        inputAlamat.setRows(5);
        jScrollPane1.setViewportView(inputAlamat);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama", "Telepon", "Alamat"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        telpAlert.setForeground(new java.awt.Color(255, 0, 0));
        telpAlert.setText("Belum Diisi");

        namaAlert.setForeground(new java.awt.Color(255, 0, 0));
        namaAlert.setText("Belum Diisi");

        alamatAlert.setForeground(new java.awt.Color(255, 0, 0));
        alamatAlert.setText("Belum Diisi");

        jLabel5.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telpAlert)
                            .addComponent(namaAlert)
                            .addComponent(alamatAlert)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(idLabel))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel5))))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(146, 146, 146))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel)
                    .addComponent(jLabel5))
                .addGap(3, 3, 3)
                .addComponent(namaAlert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(telpAlert)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(alamatAlert)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addBtn)
                .addGap(18, 18, 18)
                .addComponent(updateBtn)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn))
                .addGap(0, 82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    private void inputTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelpActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        User user = new User(inputNama.getText(), inputTelp.getText(), inputAlamat.getText());
        if(validasiInput(user) == true){
            Controller.add(user);
            fillTable();
            clearField();
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        User user = new User(inputNama.getText(), inputTelp.getText(), inputAlamat.getText(), idLabel.getText());
        boolean idTextEmty = idLabel.getText().equals("");
        System.out.println(idTextEmty);
        if(validasiInput(user) == true){
            if(idTextEmty){
                JOptionPane.showMessageDialog(null,"Silakan pilih record yang ingin dihapus");
            }else{
                Controller.update(user);
                fillTable();
                clearField();
            }
        }   
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        User user = new User(inputNama.getText(), inputTelp.getText(), inputAlamat.getText(), idLabel.getText());
        boolean idTextEmty = idLabel.getText().equals(" ");
        if(validasiInput(user) == true){
            if(idTextEmty){
                JOptionPane.showMessageDialog(null,"Silakan pilih record yang ingin dihapus");
            }else{
                Controller.delete(user);
                fillTable();
                clearField();
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        List<String> columsList = new ArrayList<String>();
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            columsList.add((String)jTable1.getValueAt(row, i));
        }
        idLabel.setText(columsList.get(0));
        inputNama.setText(columsList.get(1));
        inputTelp.setText(columsList.get(2));
        inputAlamat.setText(columsList.get(3));
        idLabel.setVisible(true);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel alamatAlert;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextArea inputAlamat;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputTelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel namaAlert;
    private javax.swing.JLabel telpAlert;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
